# Generated by Django 5.2.1 on 2025-05-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(null=True),
        ),
    ]
