# Generated by Django 5.2.1 on 2025-05-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_remove_recipe_ingredients_ingredient_recipeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipeId',
            new_name='recipe',
        ),
    ]
