# Generated by Django 5.2.1 on 2025-05-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_recipe_instruction_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
